name: Jest Test
on: [push]
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install
      run: npm install
    - name: test
      run: npm run test
  docker:
    name: Build and test Docker
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: docker build . --file Dockerfile --tag image
    - name: Start container
      run: docker run --rm -d -p 4000:4000 --name my-image image
    - name: Test image is running
      run: |
        until $(curl -X POST --silent --output /dev/null --header "content-type: application/json" \
        --data '{"operationName":null,"variables":{},"query":"{\n  jhu {\n    data {\n      total\n    }\n  }\n}\n"}' \
        --fail http://localhost:4000); do printf '.' && sleep 2; done;
    - name: Stop container
      run: docker stop my-image